development:
  adapter: mysql
  database: whurl_engine_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  encoding: utf8

test:
  adapter: mysql
  database: whurl_engine_test
  pool: 5
  timeout: 5000
  username: root
  password: password
  encoding: utf8
