# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: whurl_pub_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  encoding: utf8

test:
  adapter: mysql
  database: whurl_pub_test
  pool: 5
  timeout: 5000
  username: root
  password: password
  encoding: utf8
